### ISSUE TITLE
Why you can get rid of prepareForReuse?

### ISSUE THREAD

**Issue by liyihe96** [ashfurrow/FunctionalReactivePixels#39]
In section "Revisiting FunctionalReactivePixels", there is “We can abstract away the need to use the prepareForReuse method altogether by replacing creating a new property on FRPCell”. However, why you don't even need the "takeUntil:self.rac_prepareForReuseSignal" to get the reusable cell work?

**Comment by ashfurrow** [comment]
You do need it to work, otherwise when the cell is reused, its bindings will still be in-effect when we try and bind them again, leading to a crash. Does that make sense?

**Comment by liyihe96** [comment]
That's what I thought, the "takeUntil:" is necessary. But you did not use takeUntil in FRPCell, and nothing crashed.

    RAC(self.imageView, image) = [[RACObserve(self, photoModel.thumbnailData) 
        ignore:nil] map:^(NSData *data) 
        return [UIImage imageWithData:data];
    }];”

**Comment by ashfurrow** [comment]
That's slightly different: I'm observing on `self` the `photoModel.thumbnailData` key path, and I only bind once. In the other, I'm binding when I create the cell, and I bind to the model, not the cell.

**Comment by liyihe96** [comment]
Gotcha, thanks.

**Comment by ashfurrow** [comment]
Cool!
