### ISSUE TITLE
i download zip from github  , and then pod install,there is an error occurs:library not found for -lPods-FRP-AFImageDownloader,how can i solve it

### ISSUE THREAD

**Issue by maibou8888** [ashfurrow/FunctionalReactivePixels#41]
Hi,ash furrow,thank you for your reply,When I use your project，my OS X is 10.10.3,Xcode is 6.4,cocoapods is 0.36.4,not use rvm or rbenv and modified the Podfile.

**Comment by ashfurrow** [comment]
Hmm – not sure, but we can figure it out. First, could I ask you to tell me the versions of CocoaPods, Xcode, and OS X you're using? Are you using rvm or rbenv? Have you modified the Podfile?

**Comment by hsavit1** [comment]
+1

**Comment by hbwang85** [comment]
+1. I encounter the same issue as hsavit1, it shows 
"ld: library not found for -lPods-FRP-500px-iOS-api"
looking forward to the solution...

**Comment by ashfurrow** [comment]
Hey there!

I didn't get notified when the original poster edited their question, so sorry to have let this slip.

_Generally_, I see this kind of thing where the code is downloaded with the "Download ZIP" button on the GitHub page. The [Installing instructions](https://github.com/ashfurrow/FunctionalReactivePixels#installing) say you need to clone the repo, but they're at the bottom of the readme, so a lot of people miss them. I'll fix that later. 

In the meantime, there are two ways we can try and get it working for you:

```sh
git clone https://github.com/ashfurrow/FunctionalReactivePixels.git
cd FunctionalReactivePixels
pod install
```

Or, if you don't use CocoaPods, you can download [this folder](http://cloud.ashfurrow.com/013J0y1R3L2l) that already contains the pods, installed.

**Comment by hsavit1** [comment]
as always, thanks for the great answer @ashfurrow 

This is a pretty common issue with cocoapods. This isn't the first project I've dealt with where an error like this has occured

**Comment by ashfurrow** [comment]
OK, cool! I've updated the installation instructions with specifics. If anyone could give the README a once over and give me their opinion, I'd appreciate it. My goal is to make this project as easy as possible to play with. 

With that said, this should fix the issue, so I'm closing this. If anyone feels it should be reopened, just let me know.

**Comment by ljysdfz** [comment]
WHOOPS.. isuue happened +1
and it made no difference that the shared zip
God helps...
Just go without code through ur magnificent book :)

**Comment by ashfurrow** [comment]
@ljysdfz Hey! Sorry to hear this – is everything working now?
