### ISSUE TITLE
sentestingkit/sentestingkit.h not found xcode 7

### ISSUE THREAD

**Issue by BulletTrain** [ashfurrow/FunctionalReactivePixels#44]
Today,I update my xcode to xcode7.0.I try to run this project,but can't do that.Can you help me?

**Comment by ashfurrow** [comment]
Hmm, I'm sorry to hear that. I'll investigate and get back to you.

**Comment by ashfurrow** [comment]
I've reproduced the issue, and I'm working on a fix.

**Comment by ashfurrow** [comment]
OK, I've pushed a fix for that. Thanks for letting me know if wasn't working – please let me know if you run into any other issues!

**Comment by BulletTrain** [comment]
Thanks.It run success.

**Comment by ashfurrow** [comment]
Great!
