### ISSUE TITLE
Swift is not supported for static libraries.

### ISSUE THREAD

**Issue by AntiMoron** [ashfurrow/FunctionalReactivePixels#48]
Hello Ash Furrow,

I followed the instruction of your book.

Write ```pod 'ReactiveCocoa'```
run ```pod install``` 

This error message shows up.
```
Check dependencies

Swift is not supported for static libraries.
```
The latest ReactiveCocoa's version I fetched is ```3.0.0```

How can I make it compile?

**Comment by ashfurrow** [comment]
Hey there! Sorry you're having problems. If you specify a version of ReactiveCocoa under 3.0 it should work. 2.5 for example. The Objective-C stuff stayed the same in 3.0, so there's no benefit for this project to use it. Does that make sense?

**Comment by AntiMoron** [comment]
Wow,it compiles now. Thx Ash.

**Comment by ashfurrow** [comment]
Awesome! Glad to hear it 🎉
